safe:        false
auto:        false
source:      .
url:         http://localhost

destination: ./public_html
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    true 
markdown:    maruku
permalink:   /:title 
