safe:        false
source:      .
url:         http://localhost

destination: ./public_html
exclude:     [README.md]
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    true 
markdown:    maruku
permalink:   /:title

searchindex: yes
paginate:    10

nav:
- page: Home
  permalink: /index.html

- page: About
  permalink: /about.html

keywords: [Programming, linux, unix, how to, help, web development, java, c,c++, python, information, nation, pigeon, nation pigeon, php, css, html, software development life cycle, steampunk, anime, cyber, sci-fi, random, pete, osaka, Pete Maynard, Peter, Maynard, blog, Aberystwyth, computer science]
